name: parolpractice
services:
- name: web
  github:
    repo: sarsenbaev-bayram/parolpractice
    branch: main
  build_command: pip install -r password_app/requirements.txt
  run_command: gunicorn -w 4 -b 0.0.0.0:$PORT password_app.app:app
  envs:
  - key: FLASK_ENV
    value: production
  - key: FLASK_DEBUG
    value: "False"
  http_port: 5000
  health_check:
    http_path: /login
  http_routes:
  - path: /
    destination_name: web
databases:
- name: password-db
  engine: SQLITE
